### ISSUE TITLE
Support custom configs or custom scripts

### ISSUE THREAD

**Issue by baruchiro** [tprasadtp/ubuntu-post-install#52]
Hi, one of the features I'm looking for in this context (but after found your project I prefer it even without them), is to also reconfigure my `.bashrc` changes.

I can list some use cases in ascending order according to complexity:

 - [ ] Run custom command. For example, configure my git by `git config --global user.name "my name"`
 - [ ] re-configure my aliases, just for example `alias cd=pushd`
 - [ ] re-configure config file, for example, just download my git config file from remote URL to the right place.
 - [ ] Add lines to the `.bashrc` (or link to these lines in another file), for example, `oh-my-zsh` configs.

**Comment by tprasadtp** [comment]
- Running custom commands can be done easily but I am not in favor of adding that feature at the moment, but if there's enough demand It can be done without much effort. 

- Other features you have mentioned are per user settings and are best left for user to decide how to manage or configure them. There are lot of already existing solutions. See https://wiki.archlinux.org/index.php/Dotfiles

**Comment by baruchiro** [comment]
About `dotfiles`, I just wanted to implement the logic of, let's say, downloading an already configured file into `.post-install` folder, and link it to the right dest, if there is no link there.

But you gave me an interesting link about managing dotfiles, hope it will answer my question.
