### ISSUE TITLE
Target Packages is configured multiple times

### ISSUE THREAD

**Issue by baruchiro** [tprasadtp/ubuntu-post-install#53]
Do you expect more than one run per machine?

Because for building my config, every new software I want to install, I adding it to the config first, then running the script again.

Now I'm getting a lot of this:

```
Wed 27 Jan 21:56:58 IST 2021 [EXT] (APT) W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/github-cli.list:1
Wed 27 Jan 21:56:58 IST 2021 [EXT] (APT) W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/github-cli.list:1
Wed 27 Jan 21:56:58 IST 2021 [EXT] (APT) W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:58 and /etc/apt/sources.list.d/github-cli.list:1
```

I know this warning. I'm asking if you considering it as a bug or it just not the right using of your script.

----

BTW, sorry for just opening issues without contributing. We need to be patient, because I almost don't know bash, so I will contribute when I will feel the invest worth the value :-)

**Comment by baruchiro** [comment]
Sorry, maybe it because I installed `github-cli` before?

**Comment by tprasadtp** [comment]
This script avoids modifying `sources.list` whenever possible. Only reason you have this warning is because you have manually added those lines to sources.list.

**Comment by baruchiro** [comment]
Thanks
